// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllDrives() {
  return window['go']['main']['App']['GetAllDrives']();
}

export function GetAllFolders(arg1) {
  return window['go']['main']['App']['GetAllFolders'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
